In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/vannyzhang/Desktop/ML /DJIA.csv')
stocks = df.pivot('Date', 'Name') #改变index表示并为其命名的操作
stocks

             Open                                                          \
Name         AABA    AAPL     AMZN     AXP      BA     CAT   CSCO     CVX
Date
2006-01-03  39.69   10.34    47.47   51.70   70.40   57.87  17.21   57.25
2006-01-04  41.22   10.73    47.48   52.44   70.08   57.95  17.48   59.08
2006-01-05  40.93   10.69    47.16   51.90   70.55   59.02  17.94   58.68
2006-01-06  42.88   10.75    47.97   52.64   70.34   59.47  18.51   58.95
2006-01-09  43.10   10.96    46.55   52.82   69.28   60.45  18.97   59.49
2006-01-10  42.96   10.89    46.41   53.58   68.80   61.35  18.87   58.76
2006-01-11  42.19   11.98    45.65   53.70   69.97   60.87  18.98   59.22
2006-01-12  41.92   12.14    44.79   53.58   70.25   61.23  19.27   60.00
2006-01-13  41.00   12.14    44.48   53.70   69.64   62.02  19.13   59.89
2006-01-17  39.09   12.24    43.95   53.08   69.07   61.69  18.70   60.90
2006-01-18  35.01   11.87    43.19   52.65   68.55   62.36  18.40   61.98
2006-01-19  35.82   11.61    44.50   53.06   68.16   62.05  18.85   60.40
2006-01-20  34.44   11.33    44.23   52.59   68.10   62.51  18.91   62.00
2006-01-23  34.22   10.87    44.18   51.50   65.90   60.75  18.54   61.09
2006-01-24  34.55   11.25    43.66   51.90   67.41   60.79  18.17   62.05
2006-01-25  35.43   11.06    44.05   52.50   67.71   61.50  18.35   62.30
2006-01-26  34.94   10.65    43.95   53.15   67.44   63.30  18.57   61.50
2006-01-27  35.26   10.42    44.55   53.22   68.39   65.90  18.58   60.10
2006-01-30  35.06   10.17    45.41   53.15   68.52   66.53  18.69   60.85
2006-01-31  35.20   10.79    44.76   52.51   69.00   67.00  18.70   60.41
2006-02-01  34.45   10.71    43.92   52.45   70.00   68.10  18.40   59.38
2006-02-02  35.01   10.73    43.84   52.60   71.35   68.75  18.46   58.71
2006-02-03  34.00   10.32    37.70   52.57   71.70   68.20  18.29   58.12
2006-02-06  33.90   10.29    38.34   52.22   70.65   68.50  18.03   58.00
2006-02-07  33.01    9.75    38.08   52.10   71.30   68.30  17.84   58.54
2006-02-08  33.24    9.78    37.70   51.97   71.25   67.75  19.27   57.74
2006-02-09  33.01    9.87    38.61   52.95   71.77   69.00  19.52   58.12
2006-02-10  32.58    9.31    37.98   53.14   72.10   68.15  19.61   57.32
2006-02-13  32.21    9.52    38.25   53.00   71.95   68.30  19.62   56.63
2006-02-14  32.14    9.30    38.04   53.30   72.35   69.00  19.64   55.85
...           ...     ...      ...     ...     ...     ...    ...     ...
2017-11-16  69.80  171.18  1130.16   93.55  263.76  135.47  36.04  115.25
2017-11-17  70.81  171.04  1138.28   93.31  262.82  135.80  35.90  114.67
2017-11-20  71.60  170.29  1129.77   93.92  263.00  136.44  35.93  114.77
2017-11-21  72.66  170.78  1132.86   94.42  266.24  137.77  36.75  115.14
2017-11-22  73.02  173.36  1141.00   94.39  267.00  138.22  36.70  115.49
2017-11-24  72.47  175.10  1160.70   93.97  265.26  138.10  36.41  116.55
2017-11-27  72.82  175.05  1202.66   93.57  265.38  137.47  36.51  115.85
2017-11-28  72.25  174.30  1204.88   93.76  267.00  137.51  37.00  115.92
2017-11-29  71.61  172.63  1194.80   95.96  269.48  138.17  37.75  116.20
2017-11-30  70.31  170.43  1167.10   97.02  269.91  138.90  37.62  117.26
2017-12-01  69.80  169.95  1172.05   98.08  277.51  141.60  37.09  119.81
2017-12-04  71.06  172.48  1173.85   98.62  276.16  144.25  37.81  119.81
2017-12-05  67.10  169.06  1128.26   99.20  279.01  141.75  37.74  120.54
2017-12-06  67.78  167.50  1137.99   98.64  276.58  140.15  37.37  119.98
2017-12-07  69.75  169.03  1156.59   97.76  282.81  139.78  37.26  119.50
2017-12-08  71.00  170.49  1170.40   99.00  285.01  143.87  37.59  119.96
2017-12-11  71.70  169.20  1164.60   98.60  286.21  144.63  37.59  120.29
2017-12-12  71.07  172.15  1166.51   99.37  289.94  143.42  37.79  119.68
2017-12-13  69.80  172.50  1170.00   99.12  290.50  144.18  38.09  119.43
2017-12-14  70.60  172.40  1163.71   98.31  293.35  148.85  38.20  119.81
2017-12-15  69.35  173.63  1179.03   97.78  295.87  147.35  38.01  120.44
2017-12-18  70.54  174.88  1187.37   99.19  296.00  147.75  38.48  119.92
2017-12-19  69.70  174.99  1189.15  100.21  296.50  149.90  38.66  120.32
2017-12-20  70.60  174.87  1190.50   99.71  298.70  151.93  38.49  120.28
2017-12-21  71.00  174.17  1175.90   99.05  298.05  152.69  38.88  121.39
2017-12-22  71.42  174.68  1172.08   98.47  296.33  154.77  38.52  124.85
2017-12-26  70.94  170.80  1168.36   98.80  295.54  156.04  38.55  125.23
2017-12-27  69.77  170.10  1179.91   98.90  296.41  156.94  38.54  125.96
2017-12-28  70.12  171.00  1189.00   99.64  295.81  157.94  38.73  125.69
2017-12-29  69.79  170.52  1182.35  100.00  296.94  158.05  38.41  125.36

                              ...           Volume                          \
Name           DIS     GE     ...             MSFT         NKE         PFE
Date                          ...
2006-01-03   24.08  35.10     ...       79974418.0  18468800.0  38052400.0
2006-01-04   24.50  35.35     ...       57975661.0  15832000.0  43972000.0
2006-01-05   24.13  35.27     ...       48247610.0   9256000.0  42601900.0
2006-01-06   24.65  35.38     ...      100969092.0   7573600.0  28523900.0
2006-01-09   24.85  35.40     ...       55627836.0  10441600.0  28080300.0
2006-01-10   25.02  35.27     ...       64924946.0  11837600.0  28630300.0
2006-01-11   25.38  35.14     ...       70123544.0  10372800.0  28433800.0
2006-01-12   25.65  35.45     ...       45994725.0  11159200.0  27020300.0
2006-01-13   25.61  34.90     ...       41449046.0   9612000.0  20972000.0
2006-01-17   25.83  35.63     ...       58574807.0  11075200.0  32153700.0
2006-01-18   25.23  34.90     ...       52495587.0   9202400.0  33545600.0
2006-01-19   24.91  34.90     ...       60382450.0   8888800.0  57615600.0
2006-01-20   26.10  34.30     ...       79228490.0  16132000.0  51669200.0
2006-01-23   25.75  33.53     ...       47971611.0  38273600.0  28819100.0
2006-01-24   25.60  33.55     ...       63061743.0  16800000.0  29394200.0
2006-01-25   26.19  33.15     ...       59072711.0  10268800.0  26369500.0
2006-01-26   25.50  32.93     ...       69531321.0  15965600.0  41260900.0
2006-01-27   25.16  32.95     ...      134525193.0  17025600.0  61031700.0
2006-01-30   25.22  32.90     ...      103999604.0  78979200.0  32832700.0
2006-01-31   25.50  32.90     ...       94844406.0  20348000.0  31365100.0
2006-02-01   25.15  32.66     ...       68437410.0  35525600.0  28377800.0
2006-02-02   25.15  33.07     ...       55078684.0  20464800.0  24681700.0
2006-02-03   24.98  32.80     ...       75023515.0  15826400.0  27503200.0
2006-02-06   25.20  32.85     ...       60175657.0  19246400.0  21774400.0
2006-02-07   25.57  32.66     ...       72188789.0  10368800.0  28753100.0
2006-02-08   26.66  32.31     ...       51796468.0  18636800.0  62030800.0
2006-02-09   26.86  32.78     ...       52861644.0   9232800.0  46327300.0
2006-02-10   26.61  32.92     ...       52127000.0  10339200.0  57863000.0
2006-02-13   26.68  33.20     ...       46710435.0   9512800.0  24917300.0
2006-02-14   26.56  33.18     ...       58434046.0  11758400.0  31597500.0
...            ...    ...     ...              ...         ...         ...
2017-11-16  103.63  18.48     ...       20962750.0   8233261.0  12927777.0
2017-11-17  103.22  18.34     ...       22078993.0  15475465.0  14847477.0
2017-11-20  103.42  17.95     ...       16314978.0   8480580.0  11817430.0
2017-11-21  102.97  17.95     ...       21237454.0   9057784.0  12649953.0
2017-11-22  103.22  18.15     ...       20553089.0   8501289.0  10553135.0
2017-11-24  102.91  18.38     ...        7425603.0   3400441.0   6397307.0
2017-11-27  102.63  18.34     ...       18265242.0   7891587.0  10292760.0
2017-11-28  102.56  18.17     ...       21925959.0   8665270.0  12985786.0
2017-11-29  103.50  18.45     ...       27381109.0  12022818.0  15296837.0
2017-11-30  105.36  18.56     ...       33054647.0  12551210.0  22830776.0
2017-12-01  104.58  18.28     ...       29532132.0  10113675.0  18584945.0
2017-12-04  106.50  18.00     ...       39094880.0   7513232.0  14086848.0
2017-12-05  109.53  17.78     ...       26152261.0   8862852.0  22320611.0
2017-12-06  107.17  17.61     ...       26162054.0   7862151.0  17379224.0
2017-12-07  105.74  17.81     ...       23184547.0   6113277.0  15807772.0
2017-12-08  104.23  17.71     ...       24489106.0   6065231.0  14901108.0
2017-12-11  104.87  17.60     ...       22857854.0   9017814.0  14362928.0
2017-12-12  107.43  17.91     ...       23924105.0   7358001.0  22485913.0
2017-12-13  108.15  17.92     ...       22062679.0  16072573.0  15787247.0
2017-12-14  107.29  17.77     ...       19305961.0  13055089.0  14786943.0
2017-12-15  111.98  17.78     ...       53936687.0  15659278.0  37779932.0
2017-12-18  111.84  17.87     ...       22283752.0  12651962.0  16765145.0
2017-12-19  111.33  17.77     ...       23524787.0   8212457.0  14058532.0
2017-12-20  111.62  17.63     ...       23674931.0  12468576.0  15099152.0
2017-12-21  109.72  17.46     ...       17990745.0  14352349.0  14769378.0
2017-12-22  109.49  17.51     ...       14145841.0  20414195.0   8599248.0
2017-12-26  108.49  17.45     ...        9891237.0   4563475.0  10892371.0
2017-12-27  108.42  17.46     ...       14678025.0   8959745.0   8319672.0
2017-12-28  108.00  17.35     ...       10594344.0   3987151.0   6583899.0
2017-12-29  108.05  17.27     ...       18717406.0   5222115.0  11421487.0

                                                                      \
Name                PG        TRV         UNH        UTX          VZ
Date
2006-01-03   9741600.0  3843800.0   8070600.0  3716500.0  12903800.0
2006-01-04   6746400.0  2285900.0   5587100.0  3114500.0  31004500.0
2006-01-05   8936100.0  3069300.0   5626000.0  3118900.0  20664000.0
2006-01-06   8826300.0  2641500.0   5577800.0  2874300.0  57704300.0
2006-01-09   7715700.0  2201500.0   8831000.0  2467200.0  17600000.0
2006-01-10   8553600.0  1739000.0   6238100.0  3677300.0  30254800.0
2006-01-11   8791800.0  2425500.0   5519600.0  3161100.0  19609600.0
2006-01-12   6612800.0  2501900.0   5374100.0  4025300.0  24601600.0
2006-01-13   7146800.0  1719600.0  11005800.0  2136600.0  20380200.0
2006-01-17   5299200.0  2130800.0   6333200.0  3092600.0  18634600.0
2006-01-18   6699600.0  1458600.0   7132400.0  2574400.0  15106600.0
2006-01-19   8067300.0  3854700.0  13390900.0  2620600.0  16658200.0
2006-01-20  10493200.0  5071600.0  10091900.0  4392700.0  13577500.0
2006-01-23   9437800.0  2488800.0   9611600.0  3238400.0  10590800.0
2006-01-24   8163500.0  2910100.0   8251000.0  6805800.0  12571300.0
2006-01-25   8932300.0  2876300.0   6530200.0  6485500.0  12102300.0
2006-01-26   7007000.0  4758200.0   9954400.0  6675600.0  14539200.0
2006-01-27  11747900.0  3494100.0   6419500.0  6284200.0  15859700.0
2006-01-30   7909700.0  2702700.0   6739700.0  4657500.0  11254400.0
2006-01-31  10347600.0  3383600.0  10655300.0  3981300.0  12090900.0
2006-02-01  10829900.0  3103300.0   7522900.0  4622900.0  15500600.0
2006-02-02   9759100.0  4602700.0   6235200.0  3668600.0  10022000.0
2006-02-03   7816700.0  2267200.0   5392600.0  4889200.0  11965600.0
2006-02-06   4998800.0  2959700.0   4891700.0  3623100.0   8868000.0
2006-02-07   6405700.0  2124700.0   5175800.0  3313600.0   7631500.0
2006-02-08   7338000.0  2293800.0   7320600.0  2780900.0  20371000.0
2006-02-09   6242200.0  2778200.0   5747900.0  2973100.0  14525700.0
2006-02-10   5804900.0  1437700.0   4224000.0  2918800.0  13706300.0
2006-02-13   5198600.0  2278600.0   3357500.0  2523400.0   9949000.0
2006-02-14   7923000.0  2682400.0   4771900.0  2685300.0  16445000.0
...                ...        ...         ...        ...         ...
2017-11-16   7205106.0  2375761.0   1919644.0  2121574.0  13818031.0
2017-11-17   5941753.0  2372061.0   1887529.0  2808672.0  18933241.0
2017-11-20   4926181.0  1565634.0   2040368.0  2914911.0  18227389.0
2017-11-21   6196431.0  1128605.0   2327411.0  2493049.0  13598018.0
2017-11-22   6006917.0   779723.0   2257897.0  2860673.0  15825110.0
2017-11-24   2196665.0   305358.0    743961.0  1486366.0   5097203.0
2017-11-27   6199673.0  1349460.0   2856277.0  2569527.0  17548285.0
2017-11-28   4841259.0  1821343.0   2905679.0  2733677.0  20982501.0
2017-11-29   5158905.0  1772302.0   4247248.0  2769320.0  31034535.0
2017-11-30   9789941.0  2193898.0   6846394.0  5374407.0  33268492.0
2017-12-01   7953239.0  2549590.0   3326098.0  3881751.0  23909026.0
2017-12-04   9003702.0  2187969.0   5591486.0  2756917.0  19371014.0
2017-12-05   8683018.0  1464026.0   3246315.0  3149316.0  17574132.0
2017-12-06   6737358.0  1044778.0   2397451.0  2607428.0  17296644.0
2017-12-07   7274135.0  1081234.0   2661839.0  3608429.0  11986747.0
2017-12-08   5883357.0  1085281.0   2233273.0  2999689.0  13639852.0
2017-12-11   4855962.0  1068738.0   1599464.0  3137455.0  13542530.0
2017-12-12   6558871.0  1405529.0   2294112.0  3528266.0  22901150.0
2017-12-13   7141017.0  1328622.0   3059427.0  5207066.0  17705487.0
2017-12-14   5853524.0  1278685.0   2811707.0  3033688.0  18775429.0
2017-12-15  15924045.0  3170654.0   6293391.0  6193568.0  28935598.0
2017-12-18   7405735.0  1692799.0   3194085.0  4225081.0  15874323.0
2017-12-19   5644362.0  1393041.0   2340219.0  3643081.0  14239492.0
2017-12-20   6938546.0  1070160.0   2633241.0  3270804.0  11643501.0
2017-12-21   4860406.0   937446.0   2955289.0  3023938.0  12778136.0
2017-12-22   4919406.0   879374.0   1959734.0  1604455.0  13657808.0
2017-12-26   3431941.0   564742.0   1482438.0  1053109.0   6595751.0
2017-12-27   4276664.0   945416.0   1861932.0  1810839.0   8361890.0
2017-12-28   3005356.0   698740.0   1452571.0  1412983.0   6726276.0
2017-12-29   4346675.0   827560.0   2350169.0  1806925.0   9994742.0


Name               WMT         XOM
Date
2006-01-03  23413900.0  23873200.0
2006-01-04  14090700.0  19086600.0
2006-01-05  20759200.0  17158600.0
2006-01-06  21135000.0  17370000.0
2006-01-09  14890700.0  17339500.0
2006-01-10  13422500.0  17913400.0
2006-01-11  14179400.0  17327100.0
2006-01-12  11425700.0  21130500.0
2006-01-13  10260500.0  17075900.0
2006-01-17  17118300.0  18193400.0
2006-01-18  13217700.0  16232700.0
2006-01-19  18141900.0  18863000.0
2006-01-20  19354600.0  25995600.0
2006-01-23  15824700.0  19545900.0
2006-01-24  18189800.0  18075000.0
2006-01-25  18986800.0  24510200.0
2006-01-26  16798600.0  24562800.0
2006-01-27  13386000.0  21407600.0
2006-01-30  15269600.0  29444900.0
2006-01-31  12926900.0  24269200.0
2006-02-01  15189400.0  20581800.0
2006-02-02  18513100.0  21403400.0
2006-02-03  11329700.0  18829100.0
2006-02-06  12185300.0  18763400.0
2006-02-07  16191300.0  21137800.0
2006-02-08  12347600.0  21988500.0
2006-02-09  13131800.0  22554900.0
2006-02-10   8037800.0  26186400.0
2006-02-13   7161400.0  16837100.0
2006-02-14  14872500.0  21023400.0
...                ...         ...
2017-11-16  38122384.0  10527200.0
2017-11-17  23575513.0   9536383.0
2017-11-20  16394324.0   8468631.0
2017-11-21  12746499.0   8838367.0
2017-11-22   8918247.0   7941632.0
2017-11-24   4496117.0   3851283.0
2017-11-27   8904890.0   9127527.0
2017-11-28   8709645.0   9794574.0
2017-11-29  11424004.0   9724992.0
2017-11-30  12854680.0  18592679.0
2017-12-01   8296198.0  13779254.0
2017-12-04   8956524.0  12597705.0
2017-12-05   9010067.0   9357185.0
2017-12-06   7140986.0  13398866.0
2017-12-07   7502602.0  11359598.0
2017-12-08   5821061.0  11988633.0
2017-12-11   8928919.0   8760735.0
2017-12-12   7810642.0  11307030.0
2017-12-13   7879383.0  10172650.0
2017-12-14   9385769.0   9492394.0
2017-12-15  16142788.0  26582332.0
2017-12-18   7964436.0   9363466.0
2017-12-19  12012168.0  10285052.0
2017-12-20  10729805.0  10620305.0
2017-12-21   7369128.0  13578133.0
2017-12-22   5478682.0  10161447.0
2017-12-26   4295891.0   4777216.0
2017-12-27   5140793.0   7000612.0
2017-12-28   9763936.0   7495254.0
2017-12-29   7144273.0   8523411.0

[3020 rows x 155 columns]

In [3]:
target  = stocks[('High', 'MMM')].shift(-7)
target.head(10)

Date
2006-01-03    78.23
2006-01-04    78.20
2006-01-05    77.62
2006-01-06    77.28
2006-01-09    77.37
2006-01-10    76.91
2006-01-11    76.23
2006-01-12    75.60
2006-01-13    73.83
2006-01-17    73.43
Name: (High, MMM), dtype: float64

In [4]:
features =  stocks.values
target = target.values

In [5]:
from sklearn.preprocessing import Imputer
imp = Imputer(strategy='mean')
X_imp = imp.fit_transform(features)

In [6]:
# Normilize data, drop NaN obs
X_imp = X_imp[7:,]

import sklearn.preprocessing
X_norm = sklearn.preprocessing.normalize(X_imp)
X_norm.shape

(3013, 155)

In [7]:
np.argwhere(np.isnan(target))

array([[3013],
       [3014],
       [3015],
       [3016],
       [3017],
       [3018],
       [3019]])

In [8]:
target = target[:-7]
len(target)

3013

In [9]:
import tensorflow as tf
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

reset_graph()


n_steps = 30
n_inputs = len(stocks.columns)
n_neurons = 50
n_outputs = 1
learning_rate = 0.001
batch_size = 1
n_iterations = 10000

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.float32, [None, n_steps, n_outputs])

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

In [10]:
n_neurons = 100
n_layers = 3

layers = [tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
          for layer in range(n_layers)]
multi_layer_cell = tf.contrib.rnn.MultiRNNCell(layers)
rnn_outputs, states = tf.nn.dynamic_rnn(multi_layer_cell, X, dtype=tf.float32)
init = tf.global_variables_initializer()

In [11]:
stacked_rnn_outputs = tf.reshape(rnn_outputs, [-1, n_neurons])
stacked_outputs = tf.layers.dense(stacked_rnn_outputs, n_outputs)
outputs = tf.reshape(stacked_outputs, [batch_size, n_steps, n_outputs])

loss = tf.reduce_mean(tf.square(outputs - y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [12]:
def next_batch(X, y, batch_size, n_steps):
    diff = len(X) - n_steps
    ns = batch_size // n_steps
    t0 = np.round(np.random.rand(batch_size, 1) * diff)
    Ts = t0.astype(int) + np.arange(0., n_steps)
    Xs = X[Ts.astype(int)]
    ys =y[Ts.astype(int)]
    Xs = Xs[:, :n_inputs].reshape(batch_size, n_steps, n_inputs)
    ys = ys.reshape(batch_size, n_steps, n_outputs)
    return Xs, ys

In [13]:
with tf.Session() as sess:
    init.run()
    for iteration in range(n_iterations):
        X_batch, y_batch = next_batch(X_norm, target, batch_size, n_steps)
        sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        if iteration % 500 == 0:
            mse = loss.eval(feed_dict={X: X_batch, y: y_batch})
            print(iteration, "\tMSE:", mse)
    y_pred = sess.run(outputs, feed_dict={X: X_batch})
    saver.save(sess, "./stock_p1")

0 	MSE: 6774.1504
500 	MSE: 7729.6724
1000 	MSE: 2.8515375
1500 	MSE: 112.68967
2000 	MSE: 3462.5908
2500 	MSE: 2385.9744
3000 	MSE: 458.97305
3500 	MSE: 2689.485
4000 	MSE: 265.51553
4500 	MSE: 13.852633
5000 	MSE: 565.0734
5500 	MSE: 323.25348
6000 	MSE: 50.65159
6500 	MSE: 1298.8654
7000 	MSE: 1266.1985
7500 	MSE: 174.30247
8000 	MSE: 1118.9089
8500 	MSE: 1007.5979
9000 	MSE: 4040.4702
9500 	MSE: 616.26227

In [14]:
y_pred

array([[[ 81.76124 ],
        [100.063   ],
        [113.917915],
        [116.846085],
        [117.12248 ],
        [117.1286  ],
        [117.12869 ],
        [117.12872 ],
        [117.128716],
        [117.12874 ],
        [117.12875 ],
        [117.12874 ],
        [117.12873 ],
        [117.12874 ],
        [117.12874 ],
        [117.128746],
        [117.12872 ],
        [117.12874 ],
        [117.12874 ],
        [117.12869 ],
        [117.12873 ],
        [117.128746],
        [117.12872 ],
        [117.12871 ],
        [117.12871 ],
        [117.1287  ],
        [117.12866 ],
        [117.12868 ],
        [117.12872 ],
        [117.128746]]], dtype=float32)

In [15]:
n_steps = 30
n_inputs = len(stocks.columns)
n_neurons = 50
n_outputs = 1
learning_rate = 0.001
batch_size = 1
n_iterations = 100
lenX = len(X_norm) 
a = (np.zeros(shape=(lenX)))
with tf.Session() as sess:                       
    saver.restore(sess, "./stock_p1")
    lenst = len(X_norm) - n_steps
    j = 30
    i = 0
    while j < lenX:
        j = i + 30
        sh =  X_norm[i:j, :n_inputs].shape
        sh = int(sh[0])
        tar =  n_steps
        if sh < tar: break
        X_n= X_norm[i:j, :n_inputs].reshape(1, n_steps, n_inputs)
        y_pred = sess.run(outputs, feed_dict={X: X_n})
        y_pred = y_pred.flatten()
        a[i:j] = y_pred
        i = i + 30

INFO:tensorflow:Restoring parameters from ./stock_p1

In [16]:
len(a)

3013

In [17]:
inv = stocks[('High', 'MMM')]
price0 = inv[:-20]
price0.shape

(3000,)

In [18]:
y = target[:-13,]
y_hat = a[:-13]

In [19]:
len(y)

3000

In [23]:
len(y_hat)

3000

In [20]:
import pandas
dataset = pd.DataFrame({'price0':price0,'price7':y, 'price7_hat':y_hat})
dataset

            price0  price7  price7_hat
Date
2006-01-03   79.35   78.23   87.314613
2006-01-04   79.49   78.20  106.933670
2006-01-05   78.65   77.62  115.055038
2006-01-06   78.90   77.28  117.024002
2006-01-09   79.83   77.37  117.126541
2006-01-10   79.01   76.91  117.128662
2006-01-11   78.66   76.23  117.128716
2006-01-12   78.23   75.60  117.128723
2006-01-13   78.20   73.83  117.128723
2006-01-17   77.62   73.43  117.128738
2006-01-18   77.28   73.25  117.128761
2006-01-19   77.37   73.34  117.128769
2006-01-20   76.91   73.25  117.128754
2006-01-23   76.23   73.40  117.128799
2006-01-24   75.60   73.68  117.128746
2006-01-25   73.83   72.09  117.128754
2006-01-26   73.43   71.30  117.128708
2006-01-27   73.25   71.29  117.128723
2006-01-30   73.34   71.28  117.128761
2006-01-31   73.25   72.88  117.128738
2006-02-01   73.40   72.99  117.128700
2006-02-02   73.68   73.42  117.128716
2006-02-03   72.09   74.12  117.128723
2006-02-06   71.30   74.18  117.128723
2006-02-07   71.29   73.35  117.128723
2006-02-08   71.28   74.15  117.128716
2006-02-09   72.88   74.10  117.128738
2006-02-10   72.99   73.74  117.128708
2006-02-13   73.42   74.08  117.128723
2006-02-14   74.12   74.16  117.128738
...            ...     ...         ...
2017-10-19  219.25  233.66  131.138641
2017-10-20  221.32  231.60  121.515259
2017-10-23  222.78  231.76  117.452499
2017-10-24  238.90  232.80  117.137268
2017-10-25  237.94  232.58  117.128952
2017-10-26  238.80  232.63  117.128845
2017-10-27  234.95  230.77  117.128860
2017-10-30  233.66  230.65  117.128838
2017-10-31  231.60  229.40  117.128853
2017-11-01  231.76  228.44  117.128792
2017-11-02  232.80  228.43  117.128723
2017-11-03  232.58  229.96  117.128716
2017-11-06  232.63  228.51  117.128754
2017-11-07  230.77  229.99  117.128799
2017-11-08  230.65  229.92  117.128815
2017-11-09  229.40  233.59  117.128845
2017-11-10  228.44  235.71  117.128799
2017-11-13  228.43  233.86  117.128830
2017-11-14  229.96  232.04  117.128815
2017-11-15  228.51  234.53  117.128784
2017-11-16  229.99  235.94  117.128838
2017-11-17  229.92  238.19  117.128853
2017-11-20  233.59  243.45  117.128845
2017-11-21  235.71  243.63  117.128815
2017-11-22  233.86  244.23  117.128815
2017-11-24  232.04  240.26  117.128815
2017-11-27  234.53  241.08  117.128845
2017-11-28  235.94  241.29  117.128799
2017-11-29  238.19  241.01  117.128799
2017-11-30  243.45  240.21  117.128815

[3000 rows x 3 columns]

In [21]:
dataset["exp_profit"] = 100 * (dataset["price7_hat"] -  dataset["price0"] )/ dataset["price0"]
dataset["profit"] = 100 * (dataset["price7"] -  dataset["price0"] )/ dataset["price0"]

In [22]:
dataset.head(10)

            price0  price7  price7_hat  exp_profit    profit
Date
2006-01-03   79.35   78.23   87.314613   10.037320 -1.411468
2006-01-04   79.49   78.20  106.933670   34.524682 -1.622846
2006-01-05   78.65   77.62  115.055038   46.287398 -1.309599
2006-01-06   78.90   77.28  117.024002   48.319394 -2.053232
2006-01-09   79.83   77.37  117.126541   46.719956 -3.081548
2006-01-10   79.01   76.91  117.128662   48.245364 -2.657891
2006-01-11   78.66   76.23  117.128716   48.905054 -3.089245
2006-01-12   78.23   75.60  117.128723   49.723537 -3.361882
2006-01-13   78.20   73.83  117.128723   49.780976 -5.588235
2006-01-17   77.62   73.43  117.128738   50.900204 -5.398093

In [23]:
df_1 = dataset.sort_values(by=['exp_profit'], ascending=False)
df_1.head(10)

            price0  price7  price7_hat  exp_profit     profit
Date
2009-03-09   42.45   49.75  117.128693  175.921537  17.196702
2009-03-06   43.28   48.78  117.128708  170.630101  12.707948
2009-03-03   43.98   48.02  117.128685  166.322613   9.185994
2009-03-05   44.03   48.60  117.128693  166.020197  10.379287
2009-03-02   45.18   47.17  117.128677  159.248954   4.404604
2009-03-04   45.43   48.50  117.128708  157.822381   6.757649
2009-03-10   45.55   49.19  117.128693  157.143123   7.991218
2009-02-27   46.37   45.55  117.128700  152.595860  -1.768385
2009-03-11   47.17   47.58  117.128716  148.311884   0.869197
2009-02-25   47.45   43.28  117.128700  146.846576  -8.788198

In [24]:
df_1["level_exp_profit"] = df_1["price7_hat"] -  df_1["price0"] 
df_1["level_profit"] = df_1["price7"] -  df_1["price0"] 
df_1.head(10)

,price0,price7,price7_hat,exp_profit,profit,level_exp_profit,level_profit
Date,,,,,,,
2009-03-09,42.45,49.75,117.128693,175.921537,17.196702,74.678693,7.30
2009-03-06,43.28,48.78,117.128708,170.630101,12.707948,73.848708,5.50
2009-03-03,43.98,48.02,117.128685,166.322613,9.185994,73.148685,4.04
2009-03-05,44.03,48.60,117.128693,166.020197,10.379287,73.098693,4.57
2009-03-02,45.18,47.17,117.128677,159.248954,4.404604,71.948677,1.99
2009-03-04,45.43,48.50,117.128708,157.822381,6.757649,71.698708,3.07
2009-03-10,45.55,49.19,117.128693,157.143123,7.991218,71.578693,3.64
2009-02-27,46.37,45.55,117.128700,152.595860,-1.768385,70.758700,-0.82
2009-03-11,47.17,47.58,117.128716,148.311884,0.869197,69.958716,0.41
2009-02-25,47.45,43.28,117.128700,146.846576,-8.788198,69.678700,-4.17

In [25]:
df_1["level_exp_profit"].mean()

5.270198524780286

In [26]:
df_1["level_profit"].mean()

0.3792733333333333